sentry-redis:
  image: redis

sentry-postgres:
  image: postgres
  environment:
    POSTGRES_PASSWORD: secret
    POSTGRES_USER: sentry

sentry:
  image: sentry
  ports:
    - ${PUBLIC_PORT}:9000

  environment:
    SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
  links:
    - sentry-redis:redis
    - sentry-postgres:postgres

sentry-celery-beat:
  image: sentry-celery-beat

  environment:
    SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
  links:
    - sentry-postgres:postgres
    - sentry-redis:redis sentry celery beat

sentry-celery:
  image: sentry-celery

  environment:
    SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
  links:
    - sentry-postgres:postgres
    - sentry-redis:redis sentry celery worker

