influxdb:
  image: grafana/grafana
  ports:
    - ${PUBLIC_PORT}:3000
  environment:
    - GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL}
    - GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
    - GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    - GF_SECURITY_SECRET_KEY: ${GF_SECURITY_SECRET_KEY}
    - GF_USERS_ALLOW_SIGN_UP: ${GF_USERS_ALLOW_SIGN_UP}
    - GF_USERS_ALLOW_ORG_CREATE: ${GF_USERS_ALLOW_ORG_CREATE}
    - GF_USERS_AUTO_ASSIGN_ORG: ${GF_USERS_AUTO_ASSIGN_ORG}
    - GF_USERS_AUTO_ASSIGN_ORG_ROLE: ${GF_USERS_AUTO_ASSIGN_ORG_ROLE}
    - GF_USERS_LOGIN_HINT: ${GF_USERS_LOGIN_HINT}
    - GF_DATABASE_TYPE: ${GF_DATABASE_TYPE}
    - GF_DATABASE_HOST: ${GF_DATABASE_HOST}
    - GF_DATABASE_NAME: ${GF_DATABASE_NAME}
    - GF_DATABASE_USER: ${GF_DATABASE_USER}
    - GF_DATABASE_PASSWORD: ${GF_DATABASE_PASSWORD}
    - GF_DATABASE_PATH: ${GF_DATABASE_PATH}
    - GF_ANALYTICS_REPORTING_ENABLED: ${GF_ANALYTICS_REPORTING_ENABLED}
    - GF_ANALYTICS_GOOGLE_ANALYTICS_UA_ID: ${GF_ANALYTICS_GOOGLE_ANALYTICS_UA_ID}
